"""added unique constraint on artists

Revision ID: 4633830d6f41
Revises: ef56137a3c70
Create Date: 2024-01-08 15:51:13.550295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4633830d6f41'
down_revision: Union[str, None] = 'ef56137a3c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_full_name', 'artist', ['full_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_full_name', 'artist', type_='unique')
    # ### end Alembic commands ###
