"""added main s3url

Revision ID: f3363e4cb218
Revises: 32e418e59fc0
Create Date: 2024-01-08 15:12:42.889019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3363e4cb218'
down_revision: Union[str, None] = '32e418e59fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('s3_url', sa.String(), nullable=True))
    op.add_column('track', sa.Column('s3_etag_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 's3_etag_hash')
    op.drop_column('track', 's3_url')
    # ### end Alembic commands ###
