"""artist and sample

Revision ID: 23bfc3174d44
Revises: 
Create Date: 2024-01-02 18:56:07.782817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23bfc3174d44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('album_title', sa.String(), nullable=True),
    sa.Column('annotation', sa.String(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('rates_khz', sa.Float(), nullable=True),
    sa.Column('bitrate_kbps', sa.Float(), nullable=True),
    sa.Column('nb_channels', sa.Integer(), nullable=True),
    sa.Column('bit_depth', sa.Integer(), nullable=True),
    sa.Column('duration_secs', sa.Integer(), nullable=True),
    sa.Column('wav_s3_url', sa.String(), nullable=True),
    sa.Column('wav_s3_metadata', sa.JSON(), nullable=True),
    sa.Column('mp3_s3_url', sa.String(), nullable=True),
    sa.Column('mp3_s3_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_sample',
    sa.Column('artist_ref', sa.Integer(), nullable=True),
    sa.Column('sample_ref', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_ref'], ['artist.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_ref'], ['sample.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_sample_artist_ref'), 'artist_sample', ['artist_ref'], unique=False)
    op.create_index(op.f('ix_artist_sample_sample_ref'), 'artist_sample', ['sample_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artist_sample_sample_ref'), table_name='artist_sample')
    op.drop_index(op.f('ix_artist_sample_artist_ref'), table_name='artist_sample')
    op.drop_table('artist_sample')
    op.drop_table('sample')
    op.drop_table('artist')
    # ### end Alembic commands ###
