"""added main s3_metadata

Revision ID: ef56137a3c70
Revises: f3363e4cb218
Create Date: 2024-01-08 15:22:17.017139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef56137a3c70'
down_revision: Union[str, None] = 'f3363e4cb218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('s3_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 's3_metadata')
    # ### end Alembic commands ###
